fix build error caused by Spack 0.23.0 upgrade
define GLM_ENABLE_EXPERIMENTAL

```
8.392 In file included from /opt/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/glm-1.0.1-h4wgyipuf6wqsnlbnjhgudnl54bk5wiy/include/glm/gtx/string_cast.hpp:21,
8.392                  from /esi/opticks/sysrap/snd.cc:7:
8.392 /opt/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/glm-1.0.1-h4wgyipuf6wqsnlbnjhgudnl54bk5wiy/include/glm/gtx/../gtx/dual_quaternion.hpp:24:9: error: #error "GLM: GLM_GTX_dual_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
8.392    24 | #       error "GLM: GLM_GTX_dual_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
8.392       |         ^~~~~
```